### ISSUE TITLE
about codes

### ISSUE THREAD

**Issue by wozaimoyu** [ssh0219/hybrid_beamforming#1]
Which paper is the code from?

**Comment by ssh0219** [comment]
It's from paper: Deep-Unfolding Neural-Network Aided Hybrid Beamforming Based on Symbol-Error Probability Minimization



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 22, 2022 08:21 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ssh0219/hybrid_beamforming] about codes (Issue #1)




 
Which paper is the code from?
